apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: jud1th/slsa:sha-e652381ab776419ac430742319947f41f31ae4a5
          ports:
            - containerPort: 8080

