apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: jud1th/slsa:sha-dabebc946ed430ad5d9d897deb27558bb8d8cc8f
          ports:
            - containerPort: 8080

